#version: '3.9'
services:
  backend:
    build: ./backend
    container_name: store_backend
    ports:
      - '5000:5000'
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
    command: npm start

  frontend:
    build: ./frontend
    container_name: store_frontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api/v1
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
    stdin_open: true
    tty: true

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productos_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
